version: '2'
services:
  web:
    container_name: aqua.haus11.org
    restart: always
    build: .
    volumes:
          - .:/usr/src/app
    ports:
    - "3030:8081"
    environment:
     - NODE_ENV=production